#!/bin/sh

# Network traffic monitoring script.
# Stores how much data has been received (RX) or transmitted (TX) by reading
# system statistics.
# Notifies delta RX and delta TX since the previous time the cache was updated.
#
# If 'network-traffic -u' is run every hour, 'network-traffic -n' will show
# network traffic per hour.

interface="wlp3s0"

logfile="${XDG_CACHE_HOME:-$HOME/.cache}/netlog"
loghistfile="${XDG_CACHE_HOME:-$HOME/.cache}/netloghistory"

prevdata="$(cat "$logfile")"

rxcurrent="$(($(paste -d '+' /sys/class/net/$interface/statistics/rx_bytes)))"
txcurrent="$(($(paste -d '+' /sys/class/net/$interface/statistics/tx_bytes)))"

# If cache has been updated deltarx and deltatx will be calculated on function cache_verify().
# See lines 51 and 52.
deltarx=""
deltatx=""

print_usage() {
    printf "Usage: network-traffic [OPTION]\
        \n\
        \n\t-n: notify network traffic since last cache update.\
        \n\t-p: print network traffic since last cache update to standard output.\
        \n\
        \n\t-h: print all network traffic history.\
        \n\t-s: store network traffic data to the history file.\
        \n\t-x: clear network traffic history.\
        \n\
        \n\t-u: update network traffic cache.\n"
}

cache_verify() {
    touch $logfile

    if [[ "$(du -s $logfile | awk '{print $1}')" -eq "0" ]]; then
        echo -e \
            "WARNING: Cache should be updated before performing this operation\n" \
            "\t for the first time. To solve this issue, run:\n\n" \
            "\t network-traffic -u\n"
        print_usage 1>&2
        exit 1
    fi

    deltarx="$((($rxcurrent-${prevdata%% *})/1024))"
    deltatx="$((($txcurrent-${prevdata##* })/1024))"
}

cache_update() {
    touch $logfile
    truncate --size=0 $logfile

    echo \
        "$rxcurrent $txcurrent" > "$logfile"
}

history_clear() {
    touch $loghistfile
    truncate --size=0 $loghistfile
}

history_store(){
    touch $loghistfile

    echo \
        "$deltarx $deltatx" >> $loghistfile
}

history_print() {
    touch $loghistfile
    cat $loghistfile
}

data_print(){
    printf \
        "Interface: $(echo $interface)\n\nReceived: %s kB\nTransmitted: %s kB\n" \
        "$deltarx" "$deltatx"
}

data_notify() {
    notify-send \
        "Network traffic update" "$(data_print)"
}

case "$1" in
    # Current data
    -n*) cache_verify && data_notify;;
    -p*) cache_verify && data_print;;
    # History
    -h*) history_print;;
    -s*) cache_verify && history_store;;
    -x*) history_clear;;
    # Cache
    -u*) cache_update;;
    # Usage
	*) print_usage;;
esac
